local ADDON, ns = ...

-- Generated by ./scripts/bake-defaults.sh. Do not hand edit: set the addon up
-- in game the way it should ship, /reload so the client writes its saved
-- variables, then run ./scripts/bake-defaults.sh to rewrite this file.
--
-- One entry per setting that screen answers differently from the feature that
-- owns it, the account's in the first table and the character's in the second.
-- Core\Core.lua merges them over the two registries at load and checks every
-- key against them; the header there says why this is a capture rather than an
-- edited literal per setting.

ns.Shipped = {
	adhocZoom = 1,
	bagHover = 200,
	chatFont = 17,
	chatIcon = 24,
	chatWidth = 530,
	cooldownPoint = { "BOTTOM", "UIParent", "BOTTOM", 3, 312 },
	hitsArc = 26,
	hitsDrop = 120,
	hitsSize = 27,
	hoverSheetPoint = { "TOPRIGHT", "UIParent", "TOPRIGHT", -547, -228 },
	lootFeedPoint = { "RIGHT", "UIParent", "RIGHT", -114, -54 },
	lootFloatHold = 2.75,
	lootFloatIcon = 44,
	lootFloatRest = 75,
	lootFloatSide = "LEFT",
	lootFloatTop = 160,
	partyMiddle = { "CENTER", "UIParent", "CENTER", 4, -421 },
	playerCastPoint = { "BOTTOM", "UIParent", "BOTTOM", 0, 99 },
	questsColumnPoint = { "TOPLEFT", "UIParent", "TOPLEFT", 19, -43 },
	questsTrackerOff = true,
	raidMiddle = { "CENTER", "UIParent", "CENTER", -879, 46 },
	skinPlayerPoint = { "CENTER", "UIParent", "CENTER", -456, -282 },
	standingPoint = { "CENTER", "UIParent", "CENTER", -252, -289 },
	thankWord = "Thank you!",
	tipLinger = 1,
	tipZoom = 1.6,
	windowSpots = {
		WarriorKitBags = { "RIGHT", "UIParent", "RIGHT", -352, 59 },
		WarriorKitBreakdown = { "TOP", "UIParent", "TOP", -313, -130 },
		WarriorKitCharacter = { "RIGHT", "UIParent", "RIGHT", -1192, 157 },
		WarriorKitClutter = { "CENTER", "UIParent", "CENTER", 122, 91 },
		WarriorKitDungeons = { "LEFT", "UIParent", "LEFT", 345, 102 },
		WarriorKitMail = { "LEFT", "UIParent", "LEFT", 492, 137 },
		WarriorKitMap = { "TOPLEFT", "UIParent", "TOPLEFT", 247, -56 },
		WarriorKitMerchant = { "CENTER", "UIParent", "CENTER", 288, 109 },
		WarriorKitOptions = { "TOPLEFT", "UIParent", "TOPLEFT", 396, -18 },
		WarriorKitPerf = { "LEFT", "UIParent", "LEFT", 83, 161 },
		WarriorKitQuests = { "TOPLEFT", "UIParent", "TOPLEFT", 414, -46 },
		WarriorKitSockets = { "TOP", "UIParent", "TOP", 269, -128 },
		WarriorKitSpellbook = { "CENTER", "UIParent", "CENTER", -9, 155 },
		WarriorKitTalents = { "TOP", "UIParent", "TOP", 487, -43 },
	},
}

ns.ShippedChar = {
	figureFacing = 6.0578520552265,
	figureSheathed = false,
	lootLeather = true,
}
