local ADDON, ns = ...

-- Generated by ./scripts/bake-dungeon-art.sh. Do not hand edit.
--
-- The picture on a dungeon's card, as the loading screen the client has for it.
--
-- The Encounter Journal's art is what retail draws here and the 2.5 client does
-- not ship a byte of it: its interface manifest has no encounterjournal folder
-- at all. What it does ship is the loading screen of every instance in the
-- game, which is a painting of that place by the same artists and the picture a
-- player has already looked at on the way in.
--
-- Nothing here was typed. The instance list and the loading screen each one
-- carries come out of the 2.5 client's own Map table, the file out of
-- LoadingScreens, and the path out of ManifestInterfaceData, all through
-- scripts/bake-dungeon-art.lua. A path nobody generated is a path somebody
-- remembered, and a texture path that does not resolve draws nothing at all and
-- says nothing about it.
--
-- Several places share a picture and that is Blizzard's own filing rather than
-- a gap here: the three Coilfang wings are one screen, the four Auchindoun ones
-- are another, and the two Caverns of Time runs are a third.

local Art = {}
ns.DungeonArt = Art

Art.PLACES = {
	["Ragefire Chasm"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenRagefireChasm",
	["Wailing Caverns"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenWailingCaverns",
	["The Deadmines"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenDeadmines",
	["Shadowfang Keep"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenShadowFangKeep",
	["Blackfathom Deeps"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenBlackFathomDeeps",
	["The Stockade"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenStormwindStockade",
	["Gnomeregan"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenGnomeregan",
	["Razorfen Kraul"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenRazorfenKraul",
	["Scarlet Monastery"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenMonastery",
	["Razorfen Downs"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenRazorfenDowns",
	["Uldaman"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenUldaman",
	["Zul'Farrak"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenZulFarrak",
	["Maraudon"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenMaraudon",
	["The Temple of Atal'Hakkar"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenSunkenTemple",
	["Blackrock Depths"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenBlackrockDepths",
	["Lower Blackrock Spire"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenBlackrockSpire",
	["Upper Blackrock Spire"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenBlackrockSpire",
	["Dire Maul"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenDireMaul",
	["Scholomance"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenScholomance",
	["Stratholme"] = "Interface\\GLUES\\LOADINGSCREENS\\LoadScreenStrathome",
	["Hellfire Ramparts"] = "Interface\\GLUES\\LOADINGSCREENS\\LOADSCREENHELLFIRECITADEL",
	["The Blood Furnace"] = "Interface\\GLUES\\LOADINGSCREENS\\LOADSCREENHELLFIRECITADEL",
	["The Slave Pens"] = "Interface\\GLUES\\LOADINGSCREENS\\LOADSCREENCOILFANG",
	["The Underbog"] = "Interface\\GLUES\\LOADINGSCREENS\\LOADSCREENCOILFANG",
	["Mana-Tombs"] = "Interface\\GLUES\\LOADINGSCREENS\\LOADSCREENAUCHINDOUN",
	["Auchenai Crypts"] = "Interface\\GLUES\\LOADINGSCREENS\\LOADSCREENAUCHINDOUN",
	["Old Hillsbrad Foothills"] = "Interface\\GLUES\\LOADINGSCREENS\\LOADSCREENCAVERNSTIME",
	["Sethekk Halls"] = "Interface\\GLUES\\LOADINGSCREENS\\LOADSCREENAUCHINDOUN",
	["The Steamvault"] = "Interface\\GLUES\\LOADINGSCREENS\\LOADSCREENCOILFANG",
	["The Black Morass"] = "Interface\\GLUES\\LOADINGSCREENS\\LOADSCREENCAVERNSTIME",
	["Shadow Labyrinth"] = "Interface\\GLUES\\LOADINGSCREENS\\LOADSCREENAUCHINDOUN",
	["The Shattered Halls"] = "Interface\\GLUES\\LOADINGSCREENS\\LOADSCREENHELLFIRECITADEL",
	["The Mechanar"] = "Interface\\GLUES\\LOADINGSCREENS\\LOADSCREENTEMPESTKEEP",
	["The Botanica"] = "Interface\\GLUES\\LOADINGSCREENS\\LOADSCREENTEMPESTKEEP",
	["The Arcatraz"] = "Interface\\GLUES\\LOADINGSCREENS\\LOADSCREENTEMPESTKEEP",
}
