local ADDON, ns = ...

-- Generated by ./scripts/bake-dungeons.sh. Do not hand edit.
--
-- Which dungeons there are and what order their bosses are fought in is written
-- out by hand in scripts/bake-dungeons.lua. Every number below -- each creature
-- id, each level, each item id and each item name -- is read out of Questie's
-- own generated databases, which come from the client rather than from anybody
-- typing them. A boss name in that list that Questie cannot find in that
-- instance stops the bake, so the two halves check each other.
--
-- Where a boss stands is not here. Questie files every creature inside an
-- instance at {-1, -1}, which is its way of saying it does not know, so the
-- addon learns a position from where you were standing when the boss died.
-- Dungeons/Book.lua carries that side.

local Book = ns.DungeonBook

Book.DUNGEONS = {
	{ name = "Ragefire Chasm", era = "classic", low = 13, high = 18, bosses = {
		{ id = 11517, name = "Oggleflint", level = 16, loot = {
		} },
		{ id = 11520, name = "Taragaman the Hungerer", level = 16, loot = {
			{ 14148, "Crystalline Cuffs" },
			{ 14145, "Cursed Felblade" },
			{ 14149, "Subterranean Cape" },
			{ 14540, "Taragaman the Hungerer's Heart" },
		} },
		{ id = 11518, name = "Jergosh the Invoker", level = 16, loot = {
			{ 14147, "Cavedweller Bracers" },
			{ 14151, "Chanting Blade" },
			{ 14150, "Robe of Evocation" },
		} },
		{ id = 11519, name = "Bazzalan", level = 16, loot = {
		} },
	} },
	{ name = "Wailing Caverns", era = "classic", low = 17, high = 24, bosses = {
		{ id = 3671, name = "Lady Anacondra", level = 20, loot = {
			{ 6446, "Snakeskin Bag" },
			{ 5404, "Serpent's Shoulders" },
			{ 10412, "Belt of the Fang" },
			{ 9739, "Gem of Anacondra" },
		} },
		{ id = 3669, name = "Lord Cobrahn", level = 20, loot = {
			{ 6460, "Cobrahn's Grasp" },
			{ 10410, "Leggings of the Fang" },
			{ 6465, "Robe of the Moccasin" },
			{ 9738, "Gem of Cobrahn" },
		} },
		{ id = 3653, name = "Kresh", level = 20, loot = {
			{ 13245, "Kresh's Back" },
			{ 6447, "Worn Turtle Shell Shield" },
		} },
		{ id = 3670, name = "Lord Pythas", level = 21, loot = {
			{ 6472, "Stinging Viper" },
			{ 6473, "Armor of the Fang" },
			{ 9740, "Gem of Pythas" },
		} },
		{ id = 3674, name = "Skum", level = 21, loot = {
			{ 6449, "Glowing Lizardscale Cloak" },
			{ 6448, "Tail Spike" },
			{ 5125, "Charged Scale" },
		} },
		{ id = 3673, name = "Lord Serpentis", level = 21, loot = {
			{ 6469, "Venomstrike" },
			{ 10411, "Footpads of the Fang" },
			{ 6459, "Savage Trodders" },
			{ 5970, "Serpent Gloves" },
			{ 9741, "Gem of Serpentis" },
		} },
		{ id = 5775, name = "Verdan the Everliving", level = 21, loot = {
			{ 6631, "Living Root" },
			{ 6630, "Seedcloud Buckler" },
			{ 6629, "Sporid Cape" },
		} },
		{ id = 3654, name = "Mutanus the Devourer", level = 22, loot = {
			{ 6627, "Mutant Scale Breastplate" },
			{ 6461, "Slime-encrusted Pads" },
			{ 6463, "Deep Fathom Ring" },
			{ 10441, "Glowing Shard" },
		} },
	} },
	{ name = "The Deadmines", era = "classic", low = 17, high = 26, bosses = {
		{ id = 644, name = "Rhahk'Zor", level = 19, loot = {
			{ 872, "Rockslicer" },
			{ 5187, "Rhahk'Zor's Hammer" },
		} },
		{ id = 3586, name = "Miner Johnson", level = 19, loot = {
			{ 5443, "Gold-plated Buckler" },
			{ 5444, "Miner's Cape" },
		} },
		{ id = 642, name = "Sneed's Shredder", level = 20, loot = {
			{ 1937, "Buzz Saw" },
			{ 2169, "Buzzer Blade" },
			{ 7365, "Gnoam Sprecklesprocket" },
		} },
		{ id = 1763, name = "Gilnid", level = 20, loot = {
			{ 1156, "Lavishly Jeweled Ring" },
			{ 5199, "Smelting Pants" },
		} },
		{ id = 646, name = "Mr. Smite", level = 20, loot = {
			{ 7230, "Smite's Mighty Hammer" },
			{ 5196, "Smite's Reaver" },
			{ 5192, "Thief's Blade" },
		} },
		{ id = 647, name = "Captain Greenskin", level = 20, loot = {
			{ 5201, "Emberstone Staff" },
			{ 10403, "Blackened Defias Belt" },
			{ 5200, "Impaling Harpoon" },
		} },
		{ id = 639, name = "Edwin VanCleef", level = 21, loot = {
			{ 5193, "Cape of the Brotherhood" },
			{ 10399, "Blackened Defias Armor" },
			{ 5202, "Corsair's Overshirt" },
			{ 5191, "Cruel Barb" },
			{ 2874, "An Unsent Letter" },
			{ 3637, "Head of VanCleef" },
		} },
		{ id = 645, name = "Cookie", level = 20, loot = {
			{ 11982, "Viridian Band" },
			{ 5198, "Cookie's Stirring Rod" },
			{ 5197, "Cookie's Tenderizer" },
			{ 8490, "Cat Carrier (Siamese)" },
		} },
	} },
	{ name = "Shadowfang Keep", era = "classic", low = 22, high = 30, bosses = {
		{ id = 3914, name = "Rethilgore", level = 20, loot = {
			{ 5254, "Rugged Spaulders" },
		} },
		{ id = 4274, name = "Fenrus the Devourer", level = 25, loot = {
			{ 3230, "Black Wolf Bracers" },
			{ 6340, "Fenrus' Hide" },
		} },
		{ id = 3886, name = "Razorclaw the Butcher", level = 22, loot = {
			{ 1292, "Butcher's Cleaver" },
			{ 6226, "Bloody Apron" },
			{ 6633, "Butcher's Slicer" },
		} },
		{ id = 3887, name = "Baron Silverlaine", level = 24, loot = {
			{ 6321, "Silverlaine's Family Seal" },
			{ 6323, "Baron's Scepter" },
		} },
		{ id = 4278, name = "Commander Springvale", level = 24, loot = {
			{ 6320, "Commander's Crest" },
			{ 3191, "Arced War Axe" },
		} },
		{ id = 4279, name = "Odo the Blindwatcher", level = 24, loot = {
			{ 6319, "Girdle of the Blindwatcher" },
			{ 6318, "Odo's Ley Staff" },
		} },
		{ id = 3872, name = "Deathsworn Captain", level = 25, loot = {
			{ 6641, "Haunting Blade" },
			{ 6642, "Phantom Armor" },
		} },
		{ id = 3927, name = "Wolf Master Nandos", level = 25, loot = {
			{ 3748, "Feline Mantle" },
			{ 6314, "Wolfmaster Cape" },
		} },
		{ id = 4275, name = "Archmage Arugal", level = 26, loot = {
			{ 6392, "Belt of Arugal" },
			{ 6220, "Meteor Shard" },
			{ 6324, "Robes of Arugal" },
			{ 5442, "Head of Arugal" },
		} },
	} },
	{ name = "Blackfathom Deeps", era = "classic", low = 24, high = 32, bosses = {
		{ id = 4887, name = "Ghamoo-ra", level = 25, loot = {
			{ 6908, "Ghamoo-ra's Bind" },
			{ 6907, "Tortoise Armor" },
		} },
		{ id = 4831, name = "Lady Sarevess", level = 25, loot = {
			{ 888, "Naga Battle Gloves" },
			{ 11121, "Darkwater Talwar" },
			{ 3078, "Naga Heartpiercer" },
		} },
		{ id = 6243, name = "Gelihast", level = 26, loot = {
			{ 6906, "Algae Fists" },
			{ 6905, "Reef Axe" },
			{ 1470, "Murloc Skin Bag" },
		} },
		{ id = 12876, name = "Baron Aquanis", level = 28, loot = {
			{ 16782, "Strange Water Globe" },
		} },
		{ id = 4832, name = "Twilight Lord Kelris", level = 27, loot = {
			{ 1155, "Rod of the Sleepwalker" },
			{ 6903, "Gaze Dreamer Pants" },
			{ 5881, "Head of Kelris" },
		} },
		{ id = 4830, name = "Old Serra'kis", level = 26, loot = {
			{ 6901, "Glowing Thresher Cape" },
			{ 6904, "Bite of Serra'kis" },
			{ 6902, "Bands of Serra'kis" },
		} },
		{ id = 4829, name = "Aku'mai", level = 28, loot = {
			{ 6910, "Leech Pants" },
			{ 6911, "Moss Cinch" },
			{ 6909, "Strike of the Hydra" },
		} },
	} },
	{ name = "The Stockade", era = "classic", low = 24, high = 32, bosses = {
		{ id = 1696, name = "Targorr the Dread", level = 24, loot = {
			{ 3630, "Head of Targorr" },
		} },
		{ id = 1666, name = "Kam Deepfury", level = 27, loot = {
			{ 2280, "Kam's Walking Stick" },
			{ 3640, "Head of Deepfury" },
		} },
		{ id = 1717, name = "Hamhock", level = 28, loot = {
		} },
		{ id = 1716, name = "Bazil Thredd", level = 29, loot = {
			{ 2926, "Head of Bazil Thredd" },
			{ 2909, "Red Wool Bandana" },
		} },
		{ id = 1663, name = "Dextren Ward", level = 26, loot = {
			{ 3628, "Hand of Dextren Ward" },
			{ 2909, "Red Wool Bandana" },
		} },
		{ id = 1720, name = "Bruegal Ironknuckle", level = 26, loot = {
			{ 2942, "Iron Knuckles" },
			{ 3228, "Jimmied Handcuffs" },
			{ 2941, "Prison Shank" },
			{ 2909, "Red Wool Bandana" },
		} },
	} },
	{ name = "Gnomeregan", era = "classic", low = 29, high = 38, bosses = {
		{ id = 7361, name = "Grubbis", level = 32, loot = {
			{ 9445, "Grubbis Paws" },
		} },
		{ id = 7079, name = "Viscous Fallout", level = 30, loot = {
			{ 9454, "Acidic Walkers" },
			{ 9452, "Hydrocane" },
			{ 9453, "Toxic Revenger" },
		} },
		{ id = 6235, name = "Electrocutioner 6000", level = 32, loot = {
			{ 9447, "Electrocutioner Lagnut" },
			{ 9446, "Electrocutioner Leg" },
			{ 9448, "Spidertank Oilrag" },
			{ 6893, "Workshop Key" },
		} },
		{ id = 6229, name = "Crowd Pummeler 9-60", level = 32, loot = {
			{ 11827, "Schematic: Lil' Smoky" },
			{ 9449, "Manual Crowd Pummeler" },
			{ 9450, "Gnomebot Operating Boots" },
		} },
		{ id = 7800, name = "Mekgineer Thermaplugg", level = 34, loot = {
			{ 11828, "Schematic: Pet Bombling" },
			{ 7742, "Schematic: Gnomish Cloaking Device" },
			{ 9461, "Charged Gear" },
			{ 9492, "Electromagnetic Gigaflux Reactivator" },
			{ 6672, "Schematic: Flash Bomb" },
			{ 9458, "Thermaplugg's Central Core" },
			{ 9459, "Thermaplugg's Left Arm" },
			{ 7561, "Schematic: Goblin Jumper Cables" },
			{ 4413, "Schematic: Discombobulator Ray" },
			{ 7192, "Schematic: Goblin Rocket Boots" },
			{ 4411, "Schematic: Flame Deflector" },
			{ 7560, "Schematic: Gnomish Universal Remote" },
			{ 9299, "Thermaplugg's Safe Combination" },
		} },
	} },
	{ name = "Razorfen Kraul", era = "classic", low = 29, high = 38, bosses = {
		{ id = 6168, name = "Roogug", level = 28, loot = {
		} },
		{ id = 4424, name = "Aggem Thorncurse", level = 30, loot = {
			{ 6681, "Thornspike" },
		} },
		{ id = 4428, name = "Death Speaker Jargba", level = 30, loot = {
			{ 2816, "Death Speaker Scepter" },
			{ 6682, "Death Speaker Robes" },
			{ 6685, "Death Speaker Mantle" },
		} },
		{ id = 4420, name = "Overlord Ramtusk", level = 32, loot = {
			{ 6687, "Corpsemaker" },
			{ 6686, "Tusken Helm" },
		} },
		{ id = 4422, name = "Agathelos the Raging", level = 33, loot = {
			{ 6691, "Swinetusk Shank" },
			{ 6690, "Ferine Leggings" },
		} },
		{ id = 4421, name = "Charlga Razorflank", level = 33, loot = {
			{ 6693, "Agamaggan's Clutch" },
			{ 6694, "Heart of Agamaggan" },
			{ 6692, "Pronged Reaver" },
			{ 17008, "Small Scroll" },
			{ 5793, "Razorflank's Heart" },
			{ 5792, "Razorflank's Medallion" },
		} },
	} },
	{ name = "Scarlet Monastery: Graveyard", era = "classic", low = 26, high = 36, bosses = {
		{ id = 3983, name = "Interrogator Vishas", level = 32, loot = {
			{ 7683, "Bloody Brass Knuckles" },
			{ 7682, "Torturing Poker" },
		} },
		{ id = 4543, name = "Bloodmage Thalnos", level = 34, loot = {
			{ 7685, "Orb of the Forgotten Seer" },
			{ 7684, "Bloodmage Mantle" },
		} },
	} },
	{ name = "Scarlet Monastery: Library", era = "classic", low = 29, high = 39, bosses = {
		{ id = 3974, name = "Houndmaster Loksey", level = 34, loot = {
			{ 7710, "Loksey's Training Stick" },
			{ 7756, "Dog Training Gloves" },
		} },
		{ id = 6487, name = "Arcanist Doan", level = 37, loot = {
			{ 7714, "Hypnotic Blade" },
			{ 7713, "Illusionary Rod" },
			{ 7712, "Mantle of Doan" },
			{ 7711, "Robe of Doan" },
		} },
	} },
	{ name = "Scarlet Monastery: Armory", era = "classic", low = 32, high = 42, bosses = {
		{ id = 3975, name = "Herod", level = 40, loot = {
			{ 7718, "Herod's Shoulder" },
			{ 7719, "Raging Berserker's Helm" },
			{ 7717, "Ravager" },
		} },
	} },
	{ name = "Scarlet Monastery: Cathedral", era = "classic", low = 35, high = 45, bosses = {
		{ id = 4542, name = "High Inquisitor Fairbanks", level = 40, loot = {
			{ 19508, "Branded Leather Bracers" },
			{ 19509, "Dusty Mail Boots" },
			{ 19507, "Inquisitor's Shawl" },
		} },
		{ id = 3976, name = "Scarlet Commander Mograine", level = 42, loot = {
			{ 7726, "Aegis of the Scarlet Commander" },
			{ 7724, "Gauntlets of Divinity" },
			{ 7723, "Mograine's Might" },
			{ 10330, "Scarlet Leggings" },
		} },
		{ id = 3977, name = "High Inquisitor Whitemane", level = 42, loot = {
			{ 7721, "Hand of Righteousness" },
			{ 7722, "Triune Amulet" },
			{ 7720, "Whitemane's Chapeau" },
		} },
	} },
	{ name = "Razorfen Downs", era = "classic", low = 33, high = 45, bosses = {
		{ id = 7355, name = "Tuten'kash", level = 40, loot = {
			{ 10777, "Arachnid Gloves" },
			{ 10775, "Carapace of Tuten'kash" },
			{ 10776, "Silky Spider Cape" },
		} },
		{ id = 7357, name = "Mordresh Fire Eye", level = 39, loot = {
			{ 10771, "Deathmage Sash" },
			{ 10769, "Glowing Eye of Mordresh" },
			{ 10770, "Mordresh's Lifeless Skull" },
		} },
		{ id = 8567, name = "Glutton", level = 40, loot = {
			{ 10774, "Fleshhide Shoulders" },
			{ 10772, "Glutton's Cleaver" },
		} },
		{ id = 7354, name = "Ragglesnout", level = 40, loot = {
			{ 10768, "Boar Champion's Belt" },
			{ 10767, "Savage Boar's Guard" },
			{ 10758, "X'caliboar" },
		} },
		{ id = 7356, name = "Plaguemaw the Rotting", level = 40, loot = {
			{ 10766, "Plaguerot Sprig" },
			{ 10760, "Swine Fists" },
		} },
		{ id = 7358, name = "Amnennar the Coldbringer", level = 41, loot = {
			{ 10761, "Coldrage Dagger" },
			{ 10764, "Deathchill Armor" },
			{ 10763, "Icemetal Barbute" },
			{ 10762, "Robes of the Lich" },
			{ 10765, "Bonefingers" },
			{ 10420, "Skull of the Coldbringer" },
		} },
	} },
	{ name = "Uldaman", era = "classic", low = 36, high = 46, bosses = {
		{ id = 6910, name = "Revelosh", level = 40, loot = {
			{ 9387, "Revelosh's Boots" },
			{ 9389, "Revelosh's Spaulders" },
			{ 9388, "Revelosh's Armguards" },
			{ 9390, "Revelosh's Gloves" },
			{ 7741, "The Shaft of Tsol" },
		} },
		{ id = 6906, name = "Baelog", level = 41, loot = {
			{ 9401, "Nordic Longshank" },
			{ 9400, "Baelog's Shortbow" },
			{ 9399, "Precision Arrow" },
		} },
		{ id = 7228, name = "Ironaya", level = 40, loot = {
			{ 9409, "Ironaya's Bracers" },
			{ 9408, "Ironshod Bludgeon" },
			{ 9407, "Stoneweaver Leggings" },
		} },
		{ id = 7023, name = "Obsidian Sentinel", level = 42, loot = {
			{ 8053, "Obsidian Power Source" },
		} },
		{ id = 7206, name = "Ancient Stone Keeper", level = 44, loot = {
			{ 9410, "Cragfists" },
			{ 9411, "Rockshard Pauldrons" },
		} },
		{ id = 7291, name = "Galgann Firehammer", level = 45, loot = {
			{ 11310, "Flameseer Mantle" },
			{ 9412, "Galgann's Fireblaster" },
			{ 11311, "Emberscale Cape" },
			{ 9419, "Galgann's Firehammer" },
		} },
		{ id = 4854, name = "Grimlok", level = 45, loot = {
			{ 9416, "Grimlok's Charge" },
			{ 9415, "Grimlok's Tribal Vestments" },
			{ 9414, "Oilskin Leggings" },
			{ 7670, "Shattered Necklace Sapphire" },
		} },
		{ id = 2748, name = "Archaedas", level = 47, loot = {
			{ 9418, "Stoneslayer" },
			{ 9413, "The Rockpounder" },
			{ 11118, "Archaedic Stone" },
			{ 7672, "Shattered Necklace Power Source" },
		} },
	} },
	{ name = "Zul'Farrak", era = "classic", low = 42, high = 50, bosses = {
		{ id = 8127, name = "Antu'sul", level = 48, loot = {
			{ 9379, "Sang'thraze the Deflector" },
			{ 9641, "Lifeblood Amulet" },
			{ 9639, "The Hand of Antu'sul" },
			{ 9640, "Vice Grips" },
		} },
		{ id = 7272, name = "Theka the Martyr", level = 46, loot = {
			{ 9483, "Flaming Incinerator" },
			{ 9480, "Eyegouger" },
			{ 2040, "Troll Protector" },
			{ 5616, "Gutwrencher" },
			{ 9482, "Witch Doctor's Cane" },
			{ 9512, "Blackmetal Cape" },
			{ 9511, "Bloodletter Scalpel" },
			{ 10660, "First Mosh'aru Tablet" },
		} },
		{ id = 7271, name = "Witch Doctor Zum'rah", level = 46, loot = {
			{ 18083, "Jumanza Grips" },
			{ 18082, "Zum'rah's Vexing Cane" },
		} },
		{ id = 7796, name = "Nekrum Gutchewer", level = 46, loot = {
			{ 9480, "Eyegouger" },
			{ 9482, "Witch Doctor's Cane" },
			{ 9511, "Bloodletter Scalpel" },
			{ 9471, "Nekrum's Medallion" },
		} },
		{ id = 7275, name = "Shadowpriest Sezz'ziz", level = 47, loot = {
			{ 9470, "Bad Mojo Mask" },
			{ 9475, "Diabolic Skiver" },
			{ 9474, "Jinxed Hoodoo Kilt" },
			{ 9473, "Jinxed Hoodoo Skin" },
		} },
		{ id = 7604, name = "Sergeant Bly", level = 45, loot = {
			{ 5616, "Gutwrencher" },
			{ 9482, "Witch Doctor's Cane" },
		} },
		{ id = 7795, name = "Hydromancer Velratha", level = 46, loot = {
			{ 9483, "Flaming Incinerator" },
			{ 9481, "The Minotaur" },
			{ 5616, "Gutwrencher" },
			{ 9512, "Blackmetal Cape" },
			{ 10661, "Second Mosh'aru Tablet" },
			{ 9234, "Tiara of the Deep" },
		} },
		{ id = 7273, name = "Gahz'rilla", level = 46, loot = {
			{ 9469, "Gahz'rilla Scale Armor" },
			{ 9467, "Gahz'rilla Fang" },
			{ 8707, "Gahz'rilla's Electrified Scale" },
		} },
		{ id = 7267, name = "Chief Ukorz Sandscalp", level = 48, loot = {
			{ 9476, "Big Bad Pauldrons" },
			{ 9479, "Embrace of the Lycan" },
			{ 11086, "Jang'thraze the Protector" },
			{ 9478, "Ripsaw" },
			{ 9477, "The Chief's Enforcer" },
		} },
		{ id = 10082, name = "Zerillis", level = 45, loot = {
			{ 6440, "Brainlash" },
			{ 2040, "Troll Protector" },
			{ 12470, "Sandstalker Ankleguards" },
			{ 9512, "Blackmetal Cape" },
		} },
	} },
	{ name = "Maraudon", era = "classic", low = 46, high = 55, bosses = {
		{ id = 13282, name = "Noxxion", level = 48, loot = {
			{ 17744, "Heart of Noxxion" },
			{ 17745, "Noxious Shooter" },
			{ 17746, "Noxxion's Shackles" },
			{ 17702, "Celebrian Rod" },
		} },
		{ id = 12258, name = "Razorlash", level = 48, loot = {
			{ 17751, "Brusslehide Leggings" },
			{ 17750, "Chloromesh Girdle" },
			{ 17749, "Phytoskin Spaulders" },
			{ 17748, "Vinerot Sandals" },
			{ 4808, "Well Stone" },
		} },
		{ id = 12236, name = "Lord Vyletongue", level = 47, loot = {
			{ 17754, "Infernal Trickster Leggings" },
			{ 17752, "Satyr's Lash" },
			{ 17755, "Satyrmane Sash" },
			{ 17703, "Celebrian Diamond" },
		} },
		{ id = 12237, name = "Meshlok the Harvester", level = 48, loot = {
			{ 17767, "Bloomsprout Headpiece" },
			{ 17742, "Fungus Shroud Armor" },
			{ 17741, "Nature's Embrace" },
		} },
		{ id = 12225, name = "Celebras the Cursed", level = 49, loot = {
			{ 17738, "Claw of Celebras" },
			{ 17739, "Grovekeeper's Drape" },
			{ 17740, "Soothsayer's Headdress" },
		} },
		{ id = 12203, name = "Landslide", level = 50, loot = {
			{ 17737, "Cloud Stone" },
			{ 17943, "Fist of Stone" },
			{ 17734, "Helm of the Mountain" },
			{ 17736, "Rockgrip Gauntlets" },
		} },
		{ id = 13601, name = "Tinkerer Gizlock", level = 50, loot = {
			{ 17718, "Gizlock's Hypertech Buckler" },
			{ 17719, "Inventor's Focal Sword" },
			{ 17717, "Megashot Rifle" },
		} },
		{ id = 13596, name = "Rotgrip", level = 50, loot = {
			{ 17728, "Albino Crocscale Boots" },
			{ 17730, "Gatorbite Axe" },
			{ 17732, "Rotgrip Mantle" },
		} },
		{ id = 12201, name = "Princess Theradras", level = 51, loot = {
		} },
	} },
	{ name = "The Temple of Atal'Hakkar", era = "classic", low = 50, high = 60, bosses = {
		{ id = 8580, name = "Atal'alarion", level = 50, loot = {
			{ 10800, "Darkwater Bracers" },
			{ 10798, "Atal'alarion's Tusk Ring" },
			{ 10799, "Headspike" },
			{ 22444, "Putrid Vine" },
		} },
		{ id = 5721, name = "Dreamscythe", level = 53, loot = {
		} },
		{ id = 5720, name = "Weaver", level = 51, loot = {
		} },
		{ id = 5722, name = "Hazzas", level = 53, loot = {
		} },
		{ id = 5719, name = "Morphaz", level = 52, loot = {
			{ 20085, "Arcane Shard" },
			{ 20022, "Azure Key" },
			{ 20025, "Blood of Morphaz" },
			{ 20019, "Tooth of Morphaz" },
		} },
		{ id = 5710, name = "Jammal'an the Prophet", level = 54, loot = {
			{ 10808, "Gloves of the Atal'ai Prophet" },
			{ 10807, "Kilt of the Atal'ai Prophet" },
			{ 10806, "Vestments of the Atal'ai Prophet" },
			{ 6212, "Head of Jammal'an" },
		} },
		{ id = 5711, name = "Ogom the Wretched", level = 53, loot = {
			{ 10803, "Blade of the Wretched" },
			{ 10805, "Eater of the Dead" },
			{ 10804, "Fist of the Damned" },
		} },
		{ id = 5709, name = "Shade of Eranikus", level = 55, loot = {
			{ 10454, "Essence of Eranikus" },
		} },
		{ id = 8443, name = "Avatar of Hakkar", level = 49, loot = {
		} },
	} },
	{ name = "Blackrock Depths", era = "classic", low = 52, high = 60, bosses = {
		{ id = 9025, name = "Lord Roccor", level = 51, loot = {
			{ 22397, "Idol of Ferocity" },
			{ 11813, "Formula: Smoking Heart of the Mountain" },
			{ 22234, "Mantle of Lost Hope" },
			{ 11632, "Earthslag Shoulders" },
			{ 11630, "Rockshard Pellets" },
			{ 11631, "Stoneshell Guard" },
		} },
		{ id = 9016, name = "Bael'Gar", level = 54, loot = {
			{ 11802, "Lavacrest Leggings" },
			{ 11807, "Sash of the Burning Heart" },
			{ 11803, "Force of Magma" },
			{ 11805, "Rubidium Hammer" },
		} },
		{ id = 9319, name = "Houndmaster Grebmar", level = 52, loot = {
			{ 11627, "Fleetfoot Greaves" },
			{ 11628, "Houndmaster's Bow" },
			{ 11629, "Houndmaster's Rifle" },
			{ 11623, "Spritecaster Cape" },
		} },
		{ id = 9018, name = "High Interrogator Gerstahn", level = 52, loot = {
			{ 11626, "Blackveil Cape" },
			{ 11625, "Enthralled Sphere" },
			{ 22240, "Greaves of Withering Despair" },
			{ 11624, "Kentic Amice" },
			{ 11140, "Prison Cell Key" },
		} },
		{ id = 9024, name = "Pyromancer Loregrain", level = 52, loot = {
			{ 11747, "Flamestrider Robes" },
			{ 11207, "Formula: Enchant Weapon - Fiery Weapon" },
			{ 11750, "Kindling Stave" },
			{ 11748, "Pyric Caduceus" },
			{ 11749, "Searingscale Leggings" },
		} },
		{ id = 9017, name = "Lord Incendius", level = 55, loot = {
			{ 11764, "Cinderhide Armsplints" },
			{ 11767, "Emberplate Armguards" },
			{ 11766, "Flameweave Cuffs" },
			{ 11765, "Pyremail Wristguards" },
			{ 19268, "Ace of Elementals" },
			{ 21987, "Incendicite of Incendius" },
			{ 11126, "Tablet of Kurniya" },
		} },
		{ id = 9041, name = "Warder Stilgiss", level = 56, loot = {
			{ 11782, "Boreal Mantle" },
			{ 11783, "Chillsteel Girdle" },
			{ 22241, "Dark Warder's Pauldrons" },
			{ 11784, "Arbiter's Blade" },
		} },
		{ id = 9056, name = "Fineous Darkvire", level = 54, loot = {
			{ 11839, "Chief Architect's Monocle" },
			{ 22223, "Foreman's Head Protector" },
			{ 11842, "Lead Surveyor's Mantle" },
			{ 11840, "Master Builder's Shirt" },
			{ 11841, "Senior Designer's Pantaloons" },
			{ 10999, "Ironfel" },
		} },
		{ id = 9042, name = "Verek", level = 55, loot = {
			{ 11755, "Verek's Collar" },
			{ 22242, "Verek's Leash" },
		} },
		{ id = 8983, name = "Golem Lord Argelmach", level = 57, loot = {
			{ 11823, "Luminary Kilt" },
			{ 11669, "Naglering" },
			{ 11822, "Omnicast Boots" },
			{ 11819, "Second Wind" },
			{ 11268, "Head of Argelmach" },
			{ 11465, "Marshal Windsor's Lost Information" },
		} },
		{ id = 9537, name = "Hurley Blackbreath", level = 55, loot = {
			{ 18043, "Coal Miner Boots" },
			{ 22275, "Firemoss Boots" },
			{ 18044, "Hurley's Tankard" },
			{ 11735, "Ragefury Eyepatch" },
			{ 11312, "Lost Thunderbrew Recipe" },
		} },
		{ id = 9502, name = "Phalanx", level = 55, loot = {
			{ 11744, "Bloodfist" },
			{ 11745, "Fists of Phalanx" },
			{ 22212, "Golem Fitted Pauldrons" },
		} },
		{ id = 9499, name = "Plugger Spazzring", level = 55, loot = {
			{ 12791, "Barman Shanker" },
			{ 12793, "Mixologist's Tunic" },
			{ 18653, "Schematic: Goblin Jumper Cables XL" },
		} },
		{ id = 9156, name = "Ambassador Flamelash", level = 57, loot = {
			{ 11808, "Circle of Flame" },
			{ 11832, "Burst of Knowledge" },
			{ 11812, "Cape of the Fire Salamander" },
			{ 11814, "Molten Fists" },
			{ 11809, "Flame Wrath" },
		} },
		{ id = 8923, name = "Panzor the Invincible", level = 57, loot = {
			{ 11785, "Rock Golem Bulwark" },
			{ 11787, "Shalehusk Boots" },
			{ 22245, "Soot Encrusted Footwear" },
			{ 11786, "Stone of the Earth" },
		} },
		{ id = 9938, name = "Magmus", level = 57, loot = {
			{ 22208, "Lavastone Hammer" },
			{ 11935, "Magmus Stone" },
			{ 22400, "Libram of Truth" },
			{ 22395, "Totem of Rage" },
			{ 11746, "Golem Skull Helm" },
		} },
		{ id = 9033, name = "General Angerforge", level = 57, loot = {
			{ 11810, "Force of Will" },
			{ 11820, "Royal Decorated Armor" },
			{ 11821, "Warstrife Leggings" },
			{ 11816, "Angerforge's Battle Axe" },
			{ 11817, "Lord General's Sword" },
			{ 11464, "Marshal Windsor's Lost Information" },
		} },
		{ id = 9019, name = "Emperor Dagran Thaurissan", level = 59, loot = {
			{ 11934, "Emperor's Seal" },
			{ 11933, "Imperial Jewel" },
			{ 11684, "Ironfoe" },
			{ 11924, "Robes of the Royal Crown" },
			{ 22207, "Sash of the Grand Hunt" },
			{ 12033, "Thaurissan Family Jewels" },
			{ 11928, "Thaurissan's Royal Scepter" },
			{ 11930, "The Emperor's New Cape" },
			{ 22204, "Wristguards of Renown" },
			{ 11931, "Dreadforge Retaliator" },
			{ 11932, "Guiding Stave of Wisdom" },
			{ 11815, "Hand of Justice" },
			{ 21524, "Red Winter Hat" },
		} },
	} },
	{ name = "Lower Blackrock Spire", era = "classic", low = 55, high = 60, bosses = {
		{ id = 9196, name = "Highlord Omokk", level = 59, loot = {
			{ 13167, "Fist of Omokk" },
			{ 13168, "Plate of the Shaman King" },
			{ 13170, "Skyshroud Leggings" },
			{ 13166, "Slamshot Shoulders" },
			{ 13169, "Tressermane Leggings" },
			{ 16670, "Boots of Elements" },
			{ 12336, "Gemstone of Spirestone" },
			{ 12534, "Omokk's Head" },
		} },
		{ id = 9236, name = "Shadow Hunter Vosh'gajin", level = 58, loot = {
			{ 12651, "Blackcrow" },
			{ 13257, "Demonic Runed Spaulders" },
			{ 12654, "Doomshot" },
			{ 12626, "Funeral Cuffs" },
			{ 12653, "Riphook" },
			{ 16712, "Shadowcraft Gloves" },
			{ 13255, "Trueaim Gauntlets" },
			{ 13352, "Vosh'gajin's Snakestone" },
		} },
		{ id = 9237, name = "War Master Voone", level = 58, loot = {
			{ 22231, "Kayser's Boots of Precision" },
			{ 13179, "Brazecore Armguards" },
			{ 13173, "Flightblade Throwing Axe" },
			{ 12582, "Keris of Zul'Serak" },
			{ 13177, "Talisman of Evasion" },
			{ 16676, "Beaststalker's Gloves" },
			{ 12335, "Gemstone of Smolderthorn" },
			{ 21524, "Red Winter Hat" },
		} },
		{ id = 10596, name = "Mother Smolderweb", level = 59, loot = {
			{ 13244, "Gilded Gauntlets" },
			{ 13213, "Smolderweb's Eye" },
			{ 13183, "Venomspitter" },
			{ 16715, "Wildheart Boots" },
		} },
		{ id = 10584, name = "Urok Doomhowl", level = 60, loot = {
			{ 22232, "Marksman's Girdle" },
			{ 13259, "Ribsteel Footguards" },
			{ 13258, "Slaghide Gauntlets" },
			{ 13178, "Rosewine Circle" },
			{ 18784, "Top Half of Advanced Armorsmithing: Volume III" },
		} },
		{ id = 9736, name = "Quartermaster Zigris", level = 59, loot = {
			{ 12835, "Plans: Annihilator" },
			{ 13252, "Cloudrunner Girdle" },
			{ 13253, "Hands of Power" },
		} },
		{ id = 10220, name = "Halycon", level = 59, loot = {
			{ 22313, "Ironweave Bracers" },
			{ 13212, "Halycon's Spiked Collar" },
			{ 13210, "Pads of the Dread Wolf" },
			{ 13211, "Slashclaw Bracers" },
		} },
		{ id = 10268, name = "Gizrul the Slavener", level = 60, loot = {
			{ 13208, "Bleak Howler Armguards" },
			{ 13205, "Rhombeard Protector" },
			{ 13206, "Wolfshear Leggings" },
			{ 16718, "Wildheart Spaulders" },
		} },
		{ id = 9568, name = "Overlord Wyrmthalak", level = 60, loot = {
			{ 13163, "Relentless Scythe" },
			{ 22321, "Heart of Wyrmthalak" },
			{ 13143, "Mark of the Dragon Lord" },
			{ 13162, "Reiver Claws" },
			{ 13161, "Trindlehaven Staff" },
			{ 16679, "Beaststalker's Mantle" },
			{ 12337, "Gemstone of Bloodaxe" },
			{ 12780, "General Drakkisath's Command" },
		} },
	} },
	{ name = "Upper Blackrock Spire", era = "classic", low = 58, high = 60, bosses = {
		{ id = 9816, name = "Pyroguard Emberseer", level = 60, loot = {
			{ 12929, "Emberfury Talisman" },
			{ 12926, "Flaming Band" },
			{ 12927, "Truestrike Shoulders" },
			{ 12905, "Wildfire Cape" },
			{ 23320, "Tablet of Flame Shock VI" },
			{ 16672, "Gauntlets of Elements" },
			{ 21988, "Ember of Emberseer" },
			{ 17322, "Eye of the Emberseer" },
		} },
		{ id = 10264, name = "Solakar Flamewreath", level = 60, loot = {
			{ 12606, "Crystallized Girdle" },
			{ 12589, "Dustfeather Sash" },
			{ 12603, "Nightbrace Tunic" },
			{ 12609, "Polychromatic Visionwrap" },
			{ 16695, "Devout Mantle" },
			{ 18657, "Schematic: Hyper-Radiant Flame Reflector" },
		} },
		{ id = 10899, name = "Goraluk Anvilcrack", level = 61, loot = {
			{ 13502, "Handcrafted Mastersmith Girdle" },
			{ 12834, "Plans: Arcanite Champion" },
			{ 12837, "Plans: Masterwork Stormhammer" },
			{ 18047, "Flame Walkers" },
			{ 18779, "Bottom Half of Advanced Armorsmithing: Volume I" },
			{ 13498, "Handcrafted Mastersmith Leggings" },
			{ 18048, "Mastersmith's Hammer" },
			{ 21525, "Green Winter Hat" },
		} },
		{ id = 10509, name = "Jed Runewatcher", level = 59, loot = {
			{ 12930, "Briarwood Reed" },
			{ 12604, "Starfire Tiara" },
			{ 12605, "Serpentine Skuller" },
		} },
		{ id = 10429, name = "Warchief Rend Blackhand", level = 62, loot = {
			{ 18103, "Band of Rumination" },
			{ 12936, "Battleborn Armbraces" },
			{ 12583, "Blackhand Doomsaw" },
			{ 12940, "Dal'Rend's Sacred Charge" },
			{ 12939, "Dal'Rend's Tribal Guardian" },
			{ 18102, "Dragonrider Boots" },
			{ 12587, "Eye of Rend" },
			{ 22247, "Faith Healer's Boots" },
			{ 12590, "Felstriker" },
			{ 18104, "Feralsurge Girdle" },
			{ 12935, "Warmaster Legguards" },
			{ 16733, "Spaulders of Valor" },
			{ 12630, "Head of Rend Blackhand" },
		} },
		{ id = 10339, name = "Gyth", level = 62, loot = {
			{ 12953, "Dragoneye Coif" },
			{ 22225, "Dragonskin Cowl" },
			{ 12952, "Gyth's Skull" },
			{ 16669, "Pauldrons of Elements" },
			{ 13522, "Recipe: Flask of Chromatic Resistance" },
			{ 12960, "Tribal War Feathers" },
			{ 12871, "Chromatic Carapace" },
		} },
		{ id = 10430, name = "The Beast", level = 62, loot = {
			{ 12966, "Blackmist Armguards" },
			{ 12963, "Blademaster Leggings" },
			{ 12967, "Bloodmoon Cloak" },
			{ 12709, "Finkle's Skinner" },
			{ 12968, "Frostweaver Cape" },
			{ 12969, "Seeping Willow" },
			{ 12965, "Spiritshroud Leggings" },
			{ 12964, "Tristam Legguards" },
			{ 22311, "Ironweave Boots" },
			{ 24101, "Book of Ferocious Bite V" },
			{ 16729, "Lightforge Spaulders" },
			{ 19227, "Ace of Beasts" },
		} },
		{ id = 10363, name = "General Drakkisath", level = 62, loot = {
			{ 16674, "Beaststalker's Tunic" },
			{ 12592, "Blackblade of Shahram" },
			{ 16730, "Breastplate of Valor" },
			{ 13142, "Brigam Girdle" },
			{ 16690, "Devout Robe" },
			{ 12602, "Draconian Deflector" },
			{ 22268, "Draconic Infused Emblem" },
			{ 16700, "Dreadmist Robe" },
			{ 16726, "Lightforge Breastplate" },
			{ 16688, "Magister's Robes" },
			{ 13098, "Painweaver Band" },
			{ 22269, "Shadow Prowler's Cloak" },
			{ 16721, "Shadowcraft Tunic" },
			{ 22267, "Spellweaver's Turban" },
			{ 22253, "Tome of the Lost" },
			{ 13141, "Tooth of Gnarr" },
			{ 16666, "Vest of Elements" },
			{ 16706, "Wildheart Vest" },
			{ 15730, "Pattern: Red Dragonscale Breastplate" },
			{ 13519, "Recipe: Flask of the Titans" },
			{ 16663, "Blood of the Black Dragon Champion" },
		} },
	} },
	{ name = "Dire Maul: East", era = "classic", low = 55, high = 60, bosses = {
		{ id = 14354, name = "Pusillin", level = 57, loot = {
			{ 18267, "Recipe: Runn Tum Tuber Surprise" },
			{ 18261, "Book of Incantations" },
			{ 18249, "Crescent Key" },
		} },
		{ id = 11490, name = "Zevrim Thornhoof", level = 57, loot = {
			{ 18308, "Clever Hat" },
			{ 18319, "Fervent Helm" },
			{ 18306, "Gloves of Shadowy Mist" },
			{ 18313, "Helm of Awareness" },
			{ 18323, "Satyr's Bow" },
		} },
		{ id = 13280, name = "Hydrospawn", level = 57, loot = {
			{ 18305, "Breakwater Legguards" },
			{ 18307, "Riptide Shoes" },
			{ 18317, "Tempest Talisman" },
			{ 18322, "Waterspout Boots" },
			{ 18324, "Waveslicer" },
			{ 19268, "Ace of Elementals" },
			{ 18299, "Hydrospawn Essence" },
		} },
		{ id = 14327, name = "Lethtendris", level = 57, loot = {
			{ 18302, "Band of Vigor" },
			{ 18325, "Felhide Cap" },
			{ 18301, "Lethtendris's Wand" },
			{ 18311, "Quel'dorai Channeling Rod" },
			{ 18426, "Lethtendris's Web" },
		} },
		{ id = 11492, name = "Alzzin the Wildshaper", level = 58, loot = {
			{ 18321, "Energetic Rod" },
			{ 18312, "Energized Chestplate" },
			{ 18310, "Fiendish Machete" },
			{ 18309, "Gloves of Restoration" },
			{ 18318, "Merciful Greaves" },
			{ 18326, "Razor Gauntlets" },
			{ 18314, "Ring of Demonic Guile" },
			{ 18315, "Ring of Demonic Potency" },
			{ 18328, "Shadewood Cloak" },
			{ 18327, "Whipvine Cord" },
		} },
	} },
	{ name = "Dire Maul: West", era = "classic", low = 55, high = 60, bosses = {
		{ id = 11489, name = "Tendris Warpwood", level = 60, loot = {
			{ 18352, "Petrified Bark Shield" },
			{ 18353, "Stoneflower Staff" },
			{ 18390, "Tanglemoss Leggings" },
			{ 18393, "Warpwood Binding" },
		} },
		{ id = 11488, name = "Illyanna Ravenoak", level = 60, loot = {
			{ 18383, "Force Imbued Gauntlets" },
			{ 18349, "Gauntlets of Accuracy" },
			{ 18386, "Padre's Trousers" },
			{ 18347, "Well Balanced Axe" },
			{ 22206, "Bouquet of Red Roses" },
		} },
		{ id = 11487, name = "Magister Kalendris", level = 60, loot = {
			{ 22309, "Pattern: Big Bag of Enchantment" },
			{ 18374, "Flamescarred Shoulders" },
			{ 18350, "Amplifying Cloak" },
			{ 18397, "Elder Magus Pendant" },
			{ 18351, "Magically Sealed Bracers" },
			{ 18371, "Mindtap Talisman" },
		} },
		{ id = 11467, name = "Tsu'zee", level = 59, loot = {
			{ 18387, "Brightspark Gloves" },
			{ 18345, "Murmuring Ring" },
			{ 18346, "Threadbare Trousers" },
		} },
		{ id = 11496, name = "Immol'thar", level = 61, loot = {
			{ 18384, "Bile-etched Spaulders" },
			{ 18372, "Blade of the New Moon" },
			{ 18389, "Cloak of the Cosmos" },
			{ 18394, "Demon Howl Wristguards" },
			{ 18381, "Evil Eye Pendant" },
			{ 18391, "Eyestalk Cord" },
			{ 18379, "Odious Greaves" },
			{ 18377, "Quickdraw Gloves" },
			{ 18385, "Robe of Everlasting Night" },
			{ 18370, "Vigilance Charm" },
		} },
		{ id = 11486, name = "Prince Tortheldrin", level = 60, loot = {
			{ 18375, "Bracers of the Eclipse" },
			{ 18373, "Chestplate of Tranquility" },
			{ 18392, "Distracting Dagger" },
			{ 18380, "Eldritch Reinforced Legplates" },
			{ 18395, "Emerald Flame Ring" },
			{ 18382, "Fluctuating Cloak" },
			{ 18396, "Mind Carver" },
			{ 18378, "Silvermoon Leggings" },
			{ 18388, "Stoneshatter" },
			{ 18376, "Timeworn Mace" },
			{ 21525, "Green Winter Hat" },
		} },
	} },
	{ name = "Dire Maul: North", era = "classic", low = 57, high = 60, bosses = {
		{ id = 14326, name = "Guard Mol'dar", level = 59, loot = {
			{ 18268, "Gordok Inner Door Key" },
		} },
		{ id = 14322, name = "Stomper Kreeg", level = 59, loot = {
			{ 18425, "Kreeg's Mug" },
		} },
		{ id = 14321, name = "Guard Fengus", level = 59, loot = {
			{ 18459, "Gallant's Wristguards" },
			{ 18464, "Gordok Nose Ring" },
			{ 18451, "Hyena Hide Belt" },
			{ 18462, "Jagged Bone Fist" },
			{ 18458, "Modest Armguards" },
			{ 18463, "Ogre Pocket Knife" },
			{ 18450, "Robe of Combustion" },
			{ 18460, "Unsophisticated Hand Cannon" },
		} },
		{ id = 14323, name = "Guard Slip'kik", level = 59, loot = {
		} },
		{ id = 14325, name = "Captain Kromcrush", level = 61, loot = {
			{ 18507, "Boots of the Full Moon" },
			{ 18503, "Kromcrush's Chestplate" },
			{ 18502, "Monstrous Glaive" },
			{ 18505, "Mugger's Belt" },
		} },
		{ id = 14324, name = "Cho'Rush the Observer", level = 60, loot = {
			{ 18484, "Cho'Rush's Blade" },
			{ 18490, "Insightful Hood" },
			{ 18483, "Mana Channeling Wand" },
			{ 18485, "Observer's Shield" },
		} },
		{ id = 11501, name = "King Gordok", level = 61, loot = {
			{ 18522, "Band of the Ogre King" },
			{ 18520, "Barbarous Blade" },
			{ 18525, "Bracers of Prosperity" },
			{ 18523, "Brightly Glowing Stone" },
			{ 18526, "Crown of the Ogre King" },
			{ 18521, "Grimy Metal Boots" },
			{ 18527, "Harmonious Gauntlets" },
			{ 18524, "Leggings of Destruction" },
			{ 18780, "Top Half of Advanced Armorsmithing: Volume I" },
			{ 19258, "Ace of Warlords" },
		} },
	} },
	{ name = "Scholomance", era = "classic", low = 58, high = 60, bosses = {
		{ id = 10506, name = "Kirtonos the Herald", level = 60, loot = {
			{ 13983, "Gravestone War Axe" },
			{ 13956, "Clutch of Andros" },
			{ 14024, "Frightalon" },
			{ 13957, "Gargoyle Slashers" },
			{ 13960, "Heart of the Fiend" },
			{ 13969, "Loomguard Armbraces" },
			{ 13955, "Stoneform Shoulders" },
			{ 13967, "Windreaver Greaves" },
			{ 16734, "Boots of Valor" },
		} },
		{ id = 10503, name = "Jandice Barov", level = 61, loot = {
			{ 14543, "Darkshade Gloves" },
			{ 14545, "Ghostloom Leggings" },
			{ 18689, "Phantasmal Cloak" },
			{ 14548, "Royal Cap Spaulders" },
			{ 22394, "Staff of Metanoia" },
			{ 18690, "Wraithplate Leggings" },
			{ 14541, "Barovian Family Sword" },
			{ 16701, "Dreadmist Mantle" },
			{ 13523, "Blood of Innocents" },
			{ 13725, "Krastinov's Bag of Horrors" },
		} },
		{ id = 11622, name = "Rattlegore", level = 61, loot = {
			{ 18686, "Bone Golem Shoulders" },
			{ 14539, "Bone Ring Helm" },
			{ 14537, "Corpselight Greaves" },
			{ 14538, "Deadwalker Mantle" },
			{ 14528, "Rattlecage Buckler" },
			{ 18782, "Top Half of Advanced Armorsmithing: Volume II" },
			{ 14531, "Frightskull Shaft" },
			{ 16711, "Shadowcraft Boots" },
			{ 13873, "Viewing Room Key" },
		} },
		{ id = 10433, name = "Marduk Blackpool", level = 58, loot = {
			{ 18692, "Death Knight Sabatons" },
			{ 14576, "Ebon Hilt of Marduk" },
		} },
		{ id = 10432, name = "Vectus", level = 60, loot = {
			{ 18691, "Dark Advisor's Pendant" },
			{ 14577, "Skullsmoke Pants" },
		} },
		{ id = 10508, name = "Ras Frostwhisper", level = 62, loot = {
			{ 13314, "Alanna's Embrace" },
			{ 13521, "Recipe: Flask of Supreme Power" },
			{ 13626, "Human Head of Ras Frostwhisper" },
		} },
		{ id = 10505, name = "Instructor Malicia", level = 60, loot = {
			{ 16710, "Shadowcraft Bracers" },
			{ 12753, "Skin of Shadow" },
		} },
		{ id = 11261, name = "Doctor Theolen Krastinov", level = 60, loot = {
			{ 16684, "Magister's Gloves" },
			{ 13523, "Blood of Innocents" },
			{ 14617, "Sawbones Shirt" },
		} },
		{ id = 10901, name = "Lorekeeper Polkelt", level = 60, loot = {
			{ 16705, "Dreadmist Wraps" },
			{ 22206, "Bouquet of Red Roses" },
			{ 12753, "Skin of Shadow" },
		} },
		{ id = 10507, name = "The Ravenian", level = 60, loot = {
			{ 16716, "Wildheart Belt" },
			{ 12753, "Skin of Shadow" },
		} },
		{ id = 10504, name = "Lord Alexei Barov", level = 60, loot = {
			{ 16722, "Lightforge Bracers" },
		} },
		{ id = 10502, name = "Lady Illucia Barov", level = 60, loot = {
			{ 12753, "Skin of Shadow" },
		} },
		{ id = 1853, name = "Darkmaster Gandling", level = 61, loot = {
			{ 22433, "Don Mauricio's Band of Domination" },
			{ 16677, "Beaststalker's Cap" },
			{ 13938, "Bonecreeper Stylus" },
			{ 13398, "Boots of the Shrieker" },
			{ 16667, "Coif of Elements" },
			{ 16693, "Devout Crown" },
			{ 16698, "Dreadmist Mask" },
			{ 13937, "Headmaster's Charge" },
			{ 16731, "Helm of Valor" },
			{ 16727, "Lightforge Helm" },
			{ 16686, "Magister's Crown" },
			{ 14514, "Pattern: Robe of the Void" },
			{ 16707, "Shadowcraft Cap" },
			{ 13953, "Silent Fang" },
			{ 13944, "Tombstone Breastplate" },
			{ 13951, "Vigorsteel Vambraces" },
			{ 16720, "Wildheart Cowl" },
			{ 13964, "Witchblade" },
			{ 13501, "Recipe: Major Mana Potion" },
			{ 19276, "Ace of Portals" },
			{ 21525, "Green Winter Hat" },
		} },
	} },
	{ name = "Stratholme", era = "classic", low = 58, high = 60, bosses = {
		{ id = 10393, name = "Skul", level = 58, loot = {
			{ 13394, "Skul's Cold Embrace" },
			{ 13395, "Skul's Fingerbone Claws" },
			{ 13396, "Skul's Ghastly Touch" },
		} },
		{ id = 11058, name = "Fras Siabi", level = 61, loot = {
			{ 13172, "Siabi's Premium Tobacco" },
		} },
		{ id = 10558, name = "Hearthsinger Forresten", level = 57, loot = {
			{ 16682, "Magister's Boots" },
			{ 13379, "Piccolo of the Flaming Fire" },
			{ 13384, "Rainbow Girdle" },
			{ 13378, "Songbird Blouse" },
			{ 13383, "Woollies of the Prancing Minstrel" },
		} },
		{ id = 10516, name = "The Unforgiven", level = 57, loot = {
			{ 16717, "Wildheart Gloves" },
			{ 13404, "Mask of the Unforgiven" },
			{ 13408, "Soul Breaker" },
			{ 13409, "Tearfall Bracers" },
			{ 13405, "Wailing Nightbane Pauldrons" },
		} },
		{ id = 10808, name = "Timmy the Cruel", level = 58, loot = {
			{ 13401, "The Cruel Hand of Timmy" },
			{ 13403, "Grimgore Noose" },
			{ 16724, "Lightforge Gauntlets" },
			{ 13402, "Timmy's Galoshes" },
			{ 13400, "Vambraces of the Sadist" },
		} },
		{ id = 11032, name = "Malor the Zealous", level = 60, loot = {
		} },
		{ id = 10997, name = "Cannon Master Willey", level = 60, loot = {
			{ 12839, "Plans: Heartseeker" },
			{ 18721, "Barrage Girdle" },
			{ 13382, "Cannonball Runner" },
			{ 22403, "Diana's Pearl Necklace" },
			{ 22407, "Helm of the New Moon" },
			{ 22405, "Mantle of the Scarlet Crusade" },
			{ 13381, "Master Cannoneer Boots" },
			{ 13377, "Miniature Cannon Balls" },
			{ 22406, "Redemption" },
			{ 22404, "Willey's Back Scratcher" },
			{ 13380, "Willey's Portable Howitzer" },
			{ 16708, "Shadowcraft Spaulders" },
			{ 21524, "Red Winter Hat" },
		} },
		{ id = 10811, name = "Archivist Galford", level = 60, loot = {
			{ 13386, "Archivist Cape" },
			{ 18716, "Ash Covered Boots" },
			{ 13387, "Foresight Girdle" },
			{ 13385, "Tome of Knowledge" },
			{ 22897, "Tome of Conjure Food VII" },
			{ 16692, "Devout Gloves" },
			{ 22206, "Bouquet of Red Roses" },
		} },
		{ id = 10813, name = "Balnazzar", level = 62, loot = {
			{ 13353, "Book of the Dead" },
			{ 13359, "Crown of Tyranny" },
			{ 13348, "Demonshear" },
			{ 13369, "Fire Striders" },
			{ 13360, "Gift of the Elven Magi" },
			{ 18718, "Grand Crusader's Helm" },
			{ 18717, "Hammer of the Grand Crusader" },
			{ 18720, "Shroud of the Nathrezim" },
			{ 12103, "Star of Mystaria" },
			{ 13358, "Wyrmtongue Shoulders" },
			{ 14512, "Pattern: Truefaith Vestments" },
			{ 13520, "Recipe: Flask of Distilled Wisdom" },
			{ 16725, "Lightforge Boots" },
			{ 13250, "Head of Balnazzar" },
		} },
		{ id = 10435, name = "Magistrate Barthilas", level = 58, loot = {
			{ 23198, "Idol of Brutality" },
			{ 18722, "Death Grips" },
			{ 18727, "Crimson Felt Hat" },
			{ 18726, "Magistrate's Cuffs" },
			{ 18725, "Peacemaker" },
			{ 13376, "Royal Tribunal Cloak" },
			{ 12382, "Key to the City" },
		} },
		{ id = 10809, name = "Stonespine", level = 60, loot = {
			{ 13397, "Stoneskin Gargoyle Cape" },
			{ 13954, "Verdant Footpads" },
			{ 13399, "Gargoyle Shredder Talons" },
		} },
		{ id = 10437, name = "Nerub'enkan", level = 60, loot = {
			{ 13533, "Acid-etched Pauldrons" },
			{ 18738, "Carapace Spine Crossbow" },
			{ 18739, "Chitinous Plate Legguards" },
			{ 13531, "Crypt Stalker Leggings" },
			{ 13532, "Darkspinner Claws" },
			{ 13530, "Fangdrip Runners" },
			{ 13529, "Husk of Nerub'enkan" },
			{ 18740, "Thuzadin Sash" },
			{ 16675, "Beaststalker's Boots" },
		} },
		{ id = 10438, name = "Maleki the Pallid", level = 61, loot = {
			{ 12833, "Plans: Hammer of the Titans" },
			{ 18737, "Bone Slicing Hatchet" },
			{ 13525, "Darkbind Fingers" },
			{ 13526, "Flamescarred Girdle" },
			{ 13527, "Lavawalker Greaves" },
			{ 18735, "Maleki's Footwraps" },
			{ 18734, "Pale Moon Cloak" },
			{ 13524, "Skull of Burning Shadows" },
			{ 13528, "Twilight Void Bracers" },
			{ 16691, "Devout Sandals" },
		} },
		{ id = 10436, name = "Baroness Anastari", level = 59, loot = {
			{ 18728, "Anastari Heirloom" },
			{ 13534, "Banshee Finger" },
			{ 13539, "Banshee's Touch" },
			{ 13537, "Chillhide Bracers" },
			{ 13535, "Coldtouch Phantom Wraps" },
			{ 18729, "Screeching Bow" },
			{ 18730, "Shadowy Laced Handwraps" },
			{ 13538, "Windshrieker Pauldrons" },
			{ 16704, "Dreadmist Sandals" },
		} },
		{ id = 10439, name = "Ramstein the Gorger", level = 61, loot = {
			{ 18723, "Animated Chain Necklace" },
			{ 13373, "Band of Flesh" },
			{ 13375, "Crest of Retribution" },
			{ 13515, "Ramstein's Lightning Bolts" },
			{ 13372, "Slavedriver's Cane" },
			{ 13374, "Soulstealer Mantle" },
			{ 16737, "Gauntlets of Valor" },
			{ 12735, "Frayed Abomination Stitching" },
			{ 15880, "Head of Ramstein the Gorger" },
		} },
		{ id = 10440, name = "Baron Rivendare", level = 62, loot = {
			{ 13340, "Cape of the Black Baron" },
			{ 13344, "Dracorian Gauntlets" },
			{ 22410, "Gauntlets of Deftness" },
			{ 22411, "Helm of the Executioner" },
			{ 22408, "Ritssyn's Wand of Bad Mojo" },
			{ 13346, "Robes of the Exalted" },
			{ 13505, "Runeblade of Baron Rivendare" },
			{ 13349, "Scepter of the Unholy" },
			{ 13345, "Seal of Rivendare" },
			{ 13361, "Skullforge Reaver" },
			{ 22412, "Thuzadin Mantle" },
			{ 22409, "Tunic of the Crescent Moon" },
			{ 13368, "Bonescraper" },
			{ 16678, "Beaststalker's Pants" },
			{ 16694, "Devout Skirt" },
			{ 16699, "Dreadmist Leggings" },
			{ 16668, "Kilt of Elements" },
			{ 16732, "Legplates of Valor" },
			{ 16728, "Lightforge Legplates" },
			{ 16687, "Magister's Leggings" },
			{ 16709, "Shadowcraft Pants" },
			{ 16719, "Wildheart Kilt" },
			{ 13335, "Deathcharger's Reins" },
			{ 13251, "Head of Baron Rivendare" },
		} },
	} },
	{ name = "Hellfire Ramparts", era = "tbc", low = 59, high = 62, bosses = {
		{ id = 17306, name = "Watchkeeper Gargolmar", level = 62, loot = {
			{ 23881, "Gargolmar's Hand" },
		} },
		{ id = 17308, name = "Omor the Unscarred", level = 62, loot = {
			{ 23886, "Omor's Hoof" },
		} },
		{ id = 17537, name = "Vazruden", level = 62, loot = {
			{ 23890, "Ominous Letter" },
			{ 23892, "Ominous Letter" },
		} },
		{ id = 17536, name = "Nazan", level = 62, loot = {
			{ 29561, "Dragon Femur" },
			{ 29562, "Dragon's Tooth" },
			{ 23901, "Nazan's Head" },
		} },
	} },
	{ name = "The Blood Furnace", era = "tbc", low = 60, high = 63, bosses = {
		{ id = 17381, name = "The Maker", level = 62, loot = {
		} },
		{ id = 17380, name = "Broggok", level = 63, loot = {
		} },
		{ id = 17377, name = "Keli'dan the Breaker", level = 63, loot = {
		} },
	} },
	{ name = "The Slave Pens", era = "tbc", low = 61, high = 64, bosses = {
		{ id = 17941, name = "Mennu the Betrayer", level = 64, loot = {
			{ 29674, "Pattern: Nature Armor Kit" },
		} },
		{ id = 17991, name = "Rokmar the Crackler", level = 64, loot = {
		} },
		{ id = 17942, name = "Quagmirran", level = 64, loot = {
		} },
	} },
	{ name = "The Underbog", era = "tbc", low = 62, high = 65, bosses = {
		{ id = 17770, name = "Hungarfen", level = 65, loot = {
		} },
		{ id = 18105, name = "Ghaz'an", level = 65, loot = {
		} },
		{ id = 17826, name = "Swamplord Musel'ek", level = 65, loot = {
		} },
		{ id = 17882, name = "The Black Stalker", level = 65, loot = {
			{ 24248, "Brain of the Black Stalker" },
		} },
	} },
	{ name = "Mana-Tombs", era = "tbc", low = 64, high = 67, bosses = {
		{ id = 18341, name = "Pandemonius", level = 66, loot = {
		} },
		{ id = 18343, name = "Tavarok", level = 66, loot = {
		} },
		{ id = 18344, name = "Nexus-Prince Shaffar", level = 66, loot = {
			{ 22921, "Recipe: Major Frost Protection Potion" },
			{ 28490, "Shaffar's Wrappings" },
		} },
	} },
	{ name = "Auchenai Crypts", era = "tbc", low = 65, high = 68, bosses = {
		{ id = 18371, name = "Shirrak the Dead Watcher", level = 66, loot = {
		} },
		{ id = 18373, name = "Exarch Maladaar", level = 67, loot = {
		} },
	} },
	{ name = "Old Hillsbrad Foothills", era = "tbc", low = 66, high = 68, bosses = {
		{ id = 17848, name = "Lieutenant Drake", level = 68, loot = {
		} },
		{ id = 17862, name = "Captain Skarloc", level = 68, loot = {
			{ 22927, "Recipe: Ironshield Potion" },
		} },
		{ id = 18096, name = "Epoch Hunter", level = 68, loot = {
			{ 24173, "Design: Circlet of Arcane Might" },
		} },
	} },
	{ name = "Sethekk Halls", era = "tbc", low = 67, high = 69, bosses = {
		{ id = 18472, name = "Darkweaver Syth", level = 69, loot = {
			{ 24160, "Design: Khorium Inferno Band" },
			{ 27633, "Terokk's Mask" },
		} },
		{ id = 18473, name = "Talon King Ikiss", level = 69, loot = {
			{ 27632, "Terokk's Quill" },
		} },
	} },
	{ name = "The Steamvault", era = "tbc", low = 68, high = 70, bosses = {
		{ id = 17797, name = "Hydromancer Thespia", level = 72, loot = {
			{ 29673, "Pattern: Frost Armor Kit" },
			{ 30828, "Vial of Underworld Loam" },
		} },
		{ id = 17796, name = "Mekgineer Steamrigger", level = 72, loot = {
			{ 23887, "Schematic: Rocket Boots Xtreme" },
		} },
		{ id = 17798, name = "Warlord Kalithresh", level = 72, loot = {
			{ 24313, "Pattern: Battlecast Hood" },
		} },
	} },
	{ name = "The Black Morass", era = "tbc", low = 68, high = 70, bosses = {
		{ id = 17879, name = "Chrono Lord Deja", level = 72, loot = {
			{ 29675, "Pattern: Arcane Armor Kit" },
		} },
		{ id = 17880, name = "Temporus", level = 72, loot = {
		} },
		{ id = 17881, name = "Aeonus", level = 72, loot = {
		} },
	} },
	{ name = "Shadow Labyrinth", era = "tbc", low = 69, high = 70, bosses = {
		{ id = 18731, name = "Ambassador Hellmaw", level = 72, loot = {
		} },
		{ id = 18667, name = "Blackheart the Inciter", level = 72, loot = {
			{ 25728, "Pattern: Stylin' Purple Hat" },
			{ 30808, "Book of Fel Names" },
		} },
		{ id = 18732, name = "Grandmaster Vorpil", level = 72, loot = {
			{ 30827, "Lexicon Demonica" },
		} },
		{ id = 18708, name = "Murmur", level = 72, loot = {
			{ 24309, "Pattern: Spellstrike Pants" },
		} },
	} },
	{ name = "The Shattered Halls", era = "tbc", low = 69, high = 70, bosses = {
		{ id = 16807, name = "Grand Warlock Nethekurse", level = 71, loot = {
			{ 24312, "Pattern: Spellstrike Hood" },
			{ 23735, "Grand Warlock's Amulet" },
		} },
		{ id = 20923, name = "Blood Guard Porung", level = 72, loot = {
		} },
		{ id = 16809, name = "Warbringer O'mrogg", level = 72, loot = {
			{ 30829, "Tear of the Earthmother" },
		} },
		{ id = 16808, name = "Warchief Kargath Bladefist", level = 72, loot = {
			{ 23723, "Warchief Kargath's Fist" },
		} },
	} },
	{ name = "The Mechanar", era = "tbc", low = 69, high = 70, bosses = {
		{ id = 19218, name = "Gatewatcher Gyro-Kill", level = 72, loot = {
			{ 30436, "Jagged Blue Crystal" },
		} },
		{ id = 19710, name = "Gatewatcher Iron-Hand", level = 72, loot = {
			{ 30437, "Jagged Red Crystal" },
		} },
		{ id = 19219, name = "Mechano-Lord Capacitus", level = 72, loot = {
			{ 35582, "Schematic: Rocket Boots Xtreme Lite" },
		} },
		{ id = 19221, name = "Nethermancer Sepethrea", level = 72, loot = {
			{ 22920, "Recipe: Major Fire Protection Potion" },
		} },
		{ id = 19220, name = "Pathaleon the Calculator", level = 72, loot = {
			{ 21907, "Pattern: Arcanoweave Robe" },
			{ 31086, "Bottom Shard of the Arcatraz Key" },
		} },
	} },
	{ name = "The Botanica", era = "tbc", low = 70, high = 70, bosses = {
		{ id = 17976, name = "Commander Sarannis", level = 72, loot = {
			{ 28769, "The Keystone" },
		} },
		{ id = 17975, name = "High Botanist Freywinn", level = 72, loot = {
			{ 23617, "Plans: Earthpeace Breastplate" },
			{ 31744, "Botanist's Field Guide" },
		} },
		{ id = 17978, name = "Thorngrin the Tender", level = 72, loot = {
			{ 24310, "Pattern: Battlecast Pants" },
		} },
		{ id = 17980, name = "Laj", level = 72, loot = {
		} },
		{ id = 17977, name = "Warp Splinter", level = 72, loot = {
			{ 24311, "Pattern: Whitemend Hood" },
			{ 31085, "Top Shard of the Arcatraz Key" },
		} },
	} },
	{ name = "The Arcatraz", era = "tbc", low = 70, high = 70, bosses = {
		{ id = 20870, name = "Zereketh the Unbound", level = 72, loot = {
		} },
		{ id = 20885, name = "Dalliah the Doomsayer", level = 72, loot = {
			{ 24308, "Pattern: Whitemend Pants" },
		} },
		{ id = 20886, name = "Wrath-Scryer Soccothrates", level = 72, loot = {
		} },
		{ id = 20912, name = "Harbinger Skyriss", level = 72, loot = {
		} },
	} },
}
